version: 1

formatters:
  precise:
   format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s - %(message)s'

filters:
  context:
    (): synapse.logging.context.LoggingContextFilter
    request: ""

handlers:
  console:
    class: logging.StreamHandler
    formatter: precise
    filters: [context]
    # log to stdout, for easier use with 'docker logs'
    stream: 'ext://sys.stdout'

root:
    level: INFO
    handlers: [console]

disable_existing_loggers: false
